export const artCopy = {
  en: {
    foldTitle: "The image leaves the screen.",
    foldBody: "An open proof spread brings the two readings into one continuous paper field. The fold is a conceptual publication study, not a manufactured edition.",
    foldCaption: "Open proof spread / Concept mockup",
    sheetsCaption: "Paired art sheets / Concept presentation",
    materialTitle: "At the edge of the image.",
    materialBody: "Fibre, edge and ink suggest a quieter way to hold the current. These surface studies propose a material direction; they do not verify a paper stock or production finish.",
    materialCaption: "Paper and ink / Generated surface study",
    crest: "Crest / Detail from the original Silver artwork",
    depth: "Deep field / Detail from the original Silver artwork",
    grain: "Colour fragments / Detail from the original Chromatic artwork",
    foldAlt: "Conceptual open proof spread with original Chromatic and Silver artwork on two off-white paper pages",
    sheetsAlt: "Concept presentation of overlapping Chromatic and Silver art sheets with white margins",
    materialAlt: "Grazing-light macro of dark ink, uncoated paper fibres and a softly textured paper edge",
    crestAlt: "Close crop of the original Silver artwork showing the bright spray along the crest",
    depthAlt: "Close crop of the original Silver artwork showing deep tonal currents",
    grainAlt: "Square close crop of cyan, violet and coral fragments in the original Chromatic artwork",
    colophon: "Material / Colophon",
  },
  zh: {
    foldTitle: "图像，走出屏幕。",
    foldBody: "展开的样稿将两种读法连成一片纸面。这是出版形式的概念研究，并非已经制作的版本。",
    foldCaption: "展开样稿 / 概念效果图",
    sheetsCaption: "双幅艺术纸页 / 概念呈现",
    materialTitle: "在图像的边缘。",
    materialBody: "纤维、纸边与油墨，为流动提供一种更安静的承载方式。这些表面研究仅提出材质方向，不代表已核实的纸张或制作工艺。",
    materialCaption: "纸张与油墨 / 生成的表面研究",
    crest: "浪峰 / 原始银调作品局部",
    depth: "深处 / 原始银调作品局部",
    grain: "色彩碎片 / 原始色彩作品局部",
    foldAlt: "概念展开样稿，原始色彩与银调作品呈现于两页米白色纸面",
    sheetsAlt: "带白色页边的色彩与银调艺术纸页叠放的概念呈现",
    materialAlt: "掠射光下的深色油墨、非涂布纸纤维与细腻纸边的微距研究",
    crestAlt: "原始银调作品的局部，呈现浪峰沿线明亮的飞沫",
    depthAlt: "原始银调作品的局部，呈现深处的明暗流动",
    grainAlt: "原始色彩作品的方形局部，呈现青色、紫色与珊瑚色碎片",
    colophon: "材质 / 制作说明",
  },
} as const;