export type Language = "en" | "zh";

export const copy = {
  en: {
    nav: { editions: "Editions", process: "Process", language: "中文" },
    common: {
      viewEdition: "View edition",
      compare: "Compare readings",
      back: "Back to editions",
      chromatic: "Chromatic",
      silver: "Silver",
      pause: "Pause motion",
      resume: "Resume motion",
      reduced: "Reduced motion",
      concept: "Concept edition",
    },
    home: {
      kicker: "CHROMA / Art Editions / 01",
      title: "CHROMA",
      subtitle: "Two readings of one current.",
      instruction: "Move or touch across the image to reveal the silver underlayer.",
      introLabel: "Edition premise",
      introTitle: "One composition. Two material readings.",
      introBody: "Current One begins as a field of pressure, spray and luminous fragments. The chromatic reading carries temperature; the silver reading compresses the same marks into light, density and grain.",
      spreadLabel: "Reading 01 / Chromatic",
      spreadTitle: "Colour behaves like current.",
      spreadBody: "Cyan, violet and coral fragments travel through a midnight field. They do not decorate the wave; they describe its direction.",
      silverLabel: "Reading 02 / Silver",
      silverTitle: "Tone reveals the structure.",
      silverBody: "Without hue, the same composition becomes an index of pressure. Highlights gather along the crest while the deep field holds the image together.",
      closing: "Read the surface twice.",
    },
    editions: {
      eyebrow: "Edition index / 2026",
      title: "Current One",
      dek: "A paired visual publication studying how one scene changes when colour becomes tone.",
      chromaticBody: "The colour state makes the current legible through temperature: cool depth, warm interruption and high-frequency spray.",
      silverBody: "The silver state removes chromatic cues so that scale, edge and tonal weight become the primary reading.",
      noteTitle: "The pair is the work.",
      noteBody: "Neither image is a secondary treatment. Together they form a single edition built around comparison, attention and the physical act of revealing.",
    },
    detail: {
      eyebrow: "CHROMA / Edition 01",
      title: "Current One",
      dek: "A same-scene study in chromatic energy and silver structure.",
      selector: "Choose a reading",
      viewerTitle: "Close reading",
      viewerBody: "Select a fixed state for careful inspection, or use Compare to bring back the soft moving aperture.",
      compareMode: "Compare",
      notesTitle: "Paper-format design notes",
      notes: [
        ["Orientation", "Landscape field with a wide, low visual horizon."],
        ["Surface", "A restrained, uncoated-feeling paper direction to keep the image from becoming glossy spectacle."],
        ["Pairing", "Chromatic and Silver are intended to be viewed at equal scale, either sequentially or side by side."],
        ["Status", "These are conceptual material and format directions, not verified production specifications."],
      ],
      creditsTitle: "Credits",
      creditsBody: "Original composition and motion preview: PACHIN. CHROMA editorial expansion preserves the supplied source artwork and its aligned reveal logic.",
    },
    process: {
      eyebrow: "Method / Translation / Attention",
      title: "How one image becomes two readings.",
      intro: "The comparison is not a before-and-after. It is a controlled change of visual language across the same composition.",
      steps: [
        ["01", "Composition", "A turbulent current is built from deep mass, suspended fragments and a crest line that moves diagonally across the field."],
        ["02", "Media translation", "The chromatic state distributes depth through hue. The silver state holds every form in exactly the same place, translating difference into value and texture."],
        ["03", "Reveal", "A soft aperture removes the upper chromatic layer and exposes the aligned silver reading below. The feathered edge keeps the comparison continuous rather than binary."],
        ["04", "Publication", "The website treats the pair like a printed spread: large fields, compact captions, fixed labels and generous paper margins."],
      ],
      colophon: "Built as a static visual publication with browser-native masking and motion. Original supplied typefaces and their license notices remain bundled with the project.",
    },
  },
  zh: {
    nav: { editions: "版本", process: "过程", language: "EN" },
    common: {
      viewEdition: "查看版本",
      compare: "比较两种读法",
      back: "返回版本目录",
      chromatic: "色彩",
      silver: "银调",
      pause: "暂停动态",
      resume: "继续动态",
      reduced: "已减少动态",
      concept: "概念版本",
    },
    home: {
      kicker: "CHROMA / 艺术版本 / 01",
      title: "CHROMA",
      subtitle: "同一股流动，两种读法。",
      instruction: "移动指针或触摸画面，显露下方的银调图层。",
      introLabel: "版本命题",
      introTitle: "一个构图，两种材质读法。",
      introBody: "《流动之一》由压力、飞沫与发光碎片组成。色彩读法传递温度；银调读法则把相同笔触压缩成光、密度与颗粒。",
      spreadLabel: "读法 01 / 色彩",
      spreadTitle: "色彩如水流般运动。",
      spreadBody: "青色、紫色与珊瑚色碎片穿过午夜般的场域。它们不是装饰波浪，而是在描绘它的方向。",
      silverLabel: "读法 02 / 银调",
      silverTitle: "明暗显露结构。",
      silverBody: "褪去色相后，同一构图成为压力的索引。高光聚集在浪峰，深色场域则把画面凝聚在一起。",
      closing: "把表面读两遍。",
    },
    editions: {
      eyebrow: "版本索引 / 2026",
      title: "流动之一",
      dek: "一组双幅视觉出版物，研究当色彩转为明暗时，同一场景如何改变。",
      chromaticBody: "色彩状态以温度解释流动：冷色深处、暖色介入，以及高频飞沫。",
      silverBody: "银调状态移除色彩线索，让尺度、边缘与明暗重量成为主要读法。",
      noteTitle: "两幅合在一起，才是作品。",
      noteBody: "两张图都不是附属处理。它们共同组成一个关于比较、凝视与主动显露的版本。",
    },
    detail: {
      eyebrow: "CHROMA / 版本 01",
      title: "流动之一",
      dek: "以同一场景研究色彩能量与银调结构。",
      selector: "选择读法",
      viewerTitle: "近距离阅读",
      viewerBody: "选择固定状态以仔细观看，或选择“比较”重新启用柔和移动窗口。",
      compareMode: "比较",
      notesTitle: "纸张与版式设计说明",
      notes: [
        ["方向", "横向画幅，以宽而低的视觉地平线展开。"],
        ["表面", "偏向克制的非涂布纸触感，避免画面成为光亮奇观。"],
        ["配对", "色彩与银调应以相同比例观看，可依次阅读，也可并置比较。"],
        ["状态", "以上为概念性的材质与版式方向，并非已验证的制作规格。"],
      ],
      creditsTitle: "制作信息",
      creditsBody: "原始构图与动态预览：PACHIN。CHROMA 编辑扩展保留了所提供的原作与精准对齐的显露逻辑。",
    },
    process: {
      eyebrow: "方法 / 转译 / 凝视",
      title: "一张图，如何形成两种读法。",
      intro: "这不是前后对比，而是在同一构图上，有控制地转换视觉语言。",
      steps: [
        ["01", "构图", "汹涌的流动由深色体量、悬浮碎片与斜穿画面的浪峰线组成。"],
        ["02", "媒介转译", "色彩状态以色相分配深度；银调状态让所有形态保持完全相同的位置，把差异转译为明暗与质感。"],
        ["03", "显露", "柔和窗口移除上方色彩图层，显露精准对齐的银调读法。羽化边缘让比较保持连续，而非二元切换。"],
        ["04", "出版", "网站把这组图像当作印刷跨页处理：大幅画面、紧凑图注、固定标签与充足纸面留白。"],
      ],
      colophon: "本静态视觉出版物以浏览器原生遮罩和动态构建。项目保留了原始提供的字体及其授权说明。",
    },
  },
} as const;