/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as EditionsIndexRouteImport } from './routes/editions.index'
import { Route as EditionsCurrentOneRouteImport } from './routes/editions.current-one'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsIndexRoute = EditionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditionsRoute,
} as any)
const EditionsCurrentOneRoute = EditionsCurrentOneRouteImport.update({
  id: '/current-one',
  path: '/current-one',
  getParentRoute: () => EditionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editions': typeof EditionsRouteWithChildren
  '/process': typeof ProcessRoute
  '/editions/current-one': typeof EditionsCurrentOneRoute
  '/editions/': typeof EditionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/process': typeof ProcessRoute
  '/editions/current-one': typeof EditionsCurrentOneRoute
  '/editions': typeof EditionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editions': typeof EditionsRouteWithChildren
  '/process': typeof ProcessRoute
  '/editions/current-one': typeof EditionsCurrentOneRoute
  '/editions/': typeof EditionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/editions' | '/process' | '/editions/current-one' | '/editions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/process' | '/editions/current-one' | '/editions'
  id:
    | '__root__'
    | '/'
    | '/editions'
    | '/process'
    | '/editions/current-one'
    | '/editions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditionsRoute: typeof EditionsRouteWithChildren
  ProcessRoute: typeof ProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/': {
      id: '/editions/'
      path: '/'
      fullPath: '/editions/'
      preLoaderRoute: typeof EditionsIndexRouteImport
      parentRoute: typeof EditionsRoute
    }
    '/editions/current-one': {
      id: '/editions/current-one'
      path: '/current-one'
      fullPath: '/editions/current-one'
      preLoaderRoute: typeof EditionsCurrentOneRouteImport
      parentRoute: typeof EditionsRoute
    }
  }
}

interface EditionsRouteChildren {
  EditionsCurrentOneRoute: typeof EditionsCurrentOneRoute
  EditionsIndexRoute: typeof EditionsIndexRoute
}

const EditionsRouteChildren: EditionsRouteChildren = {
  EditionsCurrentOneRoute: EditionsCurrentOneRoute,
  EditionsIndexRoute: EditionsIndexRoute,
}

const EditionsRouteWithChildren = EditionsRoute._addFileChildren(
  EditionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditionsRoute: EditionsRouteWithChildren,
  ProcessRoute: ProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()


